version: '3'
services:
  # container for API
  dnsmasq:
    restart: always
    image: jpillora/dnsmasq:latest
    ports:
      - 53:53/udp
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro

  traefik:
    restart: always
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    depends_on:
      - dnsmasq
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=traefik
  app:
    extends:
      file: common.yaml
      service: app
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.traefik.entrypoints=http,https
      # URL to reach this container
      - "traefik.http.routers.app.rule=Host(`core.dev`)"
      # Activation of TLS
      - "traefik.http.routers.app.tls=true"
  db:
    extends:
      file: common.yaml
      service: db