version: '3'
services:
  # container for API
  traefik:
    image: "traefik:v2.2"
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Map the static conf into the container
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic conf into the container
      - ./conf/traefik-config.yml:/etc/traefik/config.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro
  app:
    build:
      context: .
    working_dir: /var/www/app
    volumes:
      - './demo:/var/www/app'
      - './conf/supervisord.conf:/etc/supervisor/supervisord.conf'
      - './conf/queue.conf:/etc/supervisor/conf.d/queue.conf'
      - './conf/nginx.conf:/etc/nginx/sites-enabled/default.conf'
      # - './conf/nginx.ssl.conf:/etc/nginx/sites-enabled/default.ssl.conf'
  db:
    image: mysql:5.7
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123